# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nduser', '0002_auto_20160124_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram', models.BinaryField(max_length=4096, null=True)),
                ('bins', models.BinaryField(max_length=4096, null=True)),
                ('region', models.IntegerField(choices=[(0, b'Entire Dataset'), (1, b'ROI (AB TODO)')], default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nduser.Channel')),
            ],
            options={
                'db_table': 'histogram',
                'managed': True,
            },
        ),
    ]
