# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduser', '0004_auto_20160202_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='s3backend',
            field=models.IntegerField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
    ]
