# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduser', '0005_project_s3backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nd_version',
            field=models.CharField(default=b'1.0', max_length=255),
        ),
    ]
