# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nduser', '0008_auto_20160621_0153'),
        ('nduser', '0006_auto_20160802_1608'),
    ]

    operations = [
    ]
