# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduser', '0010_auto_20160901_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='host',
            field=models.CharField(choices=[(b'localhost', b'default')], default=b'localhost', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='kvserver',
            field=models.CharField(choices=[(b'localhost', b'default')], default=b'localhost', max_length=255),
        ),
    ]
