# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('upload_queue', models.URLField(max_length=512, null=True)),
                ('ingest_queue', models.URLField(max_length=512, null=True)),
                ('cleanup_queue', models.URLField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(0, b'Preparing'), (1, b'Uploading'), (2, b'Complete'), (3, b'Deleted')], default=0)),
                ('dataset', models.CharField(max_length=128)),
                ('project', models.CharField(max_length=128)),
                ('channel', models.CharField(max_length=128)),
                ('resolution', models.IntegerField()),
                ('file_type', models.CharField(max_length=128)),
                ('x_start', models.IntegerField()),
                ('y_start', models.IntegerField()),
                ('z_start', models.IntegerField()),
                ('t_start', models.IntegerField()),
                ('x_stop', models.IntegerField()),
                ('y_stop', models.IntegerField()),
                ('z_stop', models.IntegerField()),
                ('t_stop', models.IntegerField()),
                ('tile_size_x', models.IntegerField()),
                ('tile_size_y', models.IntegerField()),
                ('tile_size_z', models.IntegerField()),
                ('tile_size_t', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingest_job',
            },
        ),
    ]
