# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingestjob',
            options={'managed': True},
        ),
    ]
